development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: nset_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: nset_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: nset_rails
  pool: 5
  timeout: 5000